[package]
name = "day-05"
version = "0.1.0"
authors = ["Bernd Kaiser <bk@dfjk.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
