[package]
name = "day-04"
version = "0.1.0"
authors = ["Bernd Kaiser <bk@dfjk.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false